config/routes.rb
Todone::Application.routes.draw do
  get "page/about"

  get "page/contact"
  get "page/home"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
    get 'logout' => :destroy
  end
  
  resources :todos do
    collection do
      get 'dosomething/:todo_id' => "todos#dosomething", :as => :dosomething
      post 'dosomething'
      post 'done'
      get 'done'
      post 'later'
      get 'later'
      get 'list'
    end
  end

  resources :users
  
  controller :users do
    get '/register' => :new
  end
  
  root :to => "page#home"
  

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title To→done app
    = stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection'
    = stylesheet_link_tag 'compiled/print.css', :media => 'print'
    /[if IE]
      = stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    .container
      #header.span-6
        %h1 To→done
        
      #menubar.span-12.last
      
        :textile
          *stop* making todo lists and *start* getting things done
        %ul#menu
          %li
            = link_to "Home →", page_home_url
          %li
            = link_to "About →", page_about_url
          - if session[:user_id].present?
            %li
              = link_to "List →", "/todos/list"
            %li
              = link_to "Logout &times;".html_safe, logout_url
          - else
            %li
              = link_to "Login →", login_url
            %li
              = link_to "Register →", register_url
          
      #content.span-20
        = yield
      #footer.span-20
        &copy;
        = Date.today.year
        %a{ :href => "http://www.basveeling.nl" } Bas Veeling
        |
        Inspired by the late todoneapp.com